base_url: "https://www.nseindia.com/"
timeout: 30

headers:
  User-Agent: "Mozilla"

datasets:
  market_status:
    endpoint: "api/marketStatus"
    poll_interval_sec: 10

  option_chain:
    endpoint: "/option/chain"
    poll_interval_sec: 30
    symbols:
      - NIFTY
      - BANKNIFTY
      - FINNIFTY